inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Bundler/OrderedGems:
  Enabled: false

StringLiterals:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/WordArray:
  Exclude:
    - 'db/schema.rb'

Style/SymbolArray:
  EnforcedStyle: percent
