sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3.3
env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

matrix:
  exclude:
    - rvm: 2.2
      env: DB=mysql
    - rvm: 2.2
      env: DB=sqlite

bundler_args: --path=vendor/bundle --without heroku

cache: bundler

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - sh -c "cp config/database.$DB.yml config/database.yml"
  - sh -c "if [ \"$DB\" = 'postgres' ]; then psql -c 'create database fat_free_crm_test;' -U postgres; fi"
  - sh -c "if [ \"$DB\" = 'mysql' ]; then mysql -e 'create database fat_free_crm_test;'; fi"
  - "RAILS_ENV=test bundle exec rake spec:preparedb"

# Run specs
script: 
  - "RAILS_ENV=test bundle exec rake spec:models"
  - "RAILS_ENV=test bundle exec rake spec:mailers"
  - "RAILS_ENV=test bundle exec rake spec:controllers"
  - "RAILS_ENV=test bundle exec rake spec:helpers"
  - "RAILS_ENV=test bundle exec rake spec:lib"
  - "RAILS_ENV=test bundle exec rake spec:mailers"
  - "RAILS_ENV=test bundle exec rake spec:models"
  - "RAILS_ENV=test bundle exec rake spec:routing"
  - "RAILS_ENV=test bundle exec rake spec:views"
  - "RAILS_ENV=test bundle exec rake spec:features"


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/859260451e154d78c1be
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
