version: '3'
services:
  web:
    build: .
    links:
      - db
    ports:
      - "80:80"
    volumes:
      - gems:/usr/local/rvm/gems
    environment:
      RAILS_ENV: 'production'
      PASSENGER_APP_ENV: 'production'
  db:
    image: postgres:9.5
volumes:
  gems: {}
