# Defaul applications settings to be loaded during installation:
#
#   rake db:settings:load
#
:tabs:
  - :active   : true
    :text     : Dashboard
    :url      : /
  - :active   : false
    :text     : Tasks
    :url      : /tasks
  - :active   : false
    :text     : Campaigns
    :url      : /campaigns
  - :active   : false
    :text     : Leads
    :url      : /leads
  - :active   : false
    :text     : Accounts
    :url      : /accounts
  - :active   : false
    :text     : Contacts
    :url      : /contacts
  - :active   : false
    :text     : Opportunities
    :url      : /opportunities

campaign_status:
  :planned       : Planned
  :started       : Started
  :completed     : Completed
  :on_hold       : On Hold
  :called_off    : Called Off

campaign_status_color:
  :planned       : palegreen
  :started       : paleturquoise
  :completed     : bisque
  :on_hold       : pink
  :called_off    : thistle

lead_status:
  :new           : New
  :contacted     : Contacted
  :converted     : Converted
  :rejected      : Rejected

lead_status_color:
  :new           : palegreen
  :contacted     : paleturquoise
  :converted     : bisque
  :rejected      : thistle

lead_source:
  :campaign      : Campaign
  :cold_call     : Cold Call
  :conference    : Conference
  :online        : Online Marketing
  :referral      : Referral
  :self          : Self Generated
  :web           : Web Site
  :word_of_mouth : Word of Mouth
  :other         : Other

# Use array of hashes for now to preserve sort order. For Ruby 1.9 or later
# we can use regular hash since its insertion order will be preserved.
opportunity_stage:
  - - Prospecting
    - :prospecting
  - - Qualification
    - :qualification
  - - Analysis
    - :analysis
  - - Presentation
    - :presentation
  - - Proposal
    - :proposal
  - - Negotiation
    - :negotiation
  - - Final Review
    - :final_review
  - - Closed/Won
    - :won
  - - Closed/Lost
    - :lost

opportunity_stage_color:
  :prospecting   : lavender
  :qualification : paleturquoise
  :analysis      : mistyrose
  :presentation  : wheat
  :proposal      : thistle
  :negotiation   : skyblue
  :final_review  : aquamarine
  :won           : lightgreen
  :lost          : pink

task_category:
  :call          : Call
  :email         : Email
  :folowup       : Follow-up
  :lunch         : Lunch
  :meeting       : Meeting
  :money         : Money
  :presentation  : Presentation
  :trip          : Trip

task_category_color:
  :call          : lavender
  :email         : paleturquoise
  :folowup       : mistyrose
  :lunch         : wheat
  :meeting       : thistle
  :money         : lightgreen
  :presentation  : aquamarine
  :trip          : skyblue

task_bucket:
  - - Overdue
    - :overdue
  - - As Soon As Possible
    - :due_asap
  - - Today
    - :due_today
  - - Tomorrow
    - :due_tomorrow
  - - This Week
    - :due_this_week
  - - Next Week
    - :due_next_week
  - - Sometime Later
    - :due_later

task_completed:
  - - Today
    - :completed_today
  - - Yesterday
    - :completed_yesterday
  - - Last week
    - :completed_last_week
  - - This month
    - :completed_this_month
  - - Last month
    - :completed_last_month
