# Defaul applications settings to be loaded during installation:
#
#   rake db:settings:load
#
:tabs:
  - :active: true
    :text: Home
    :url: /
  - :active: false
    :text: Accounts
    :url: /accounts
  - :active: false
    :text: Campaigns
    :url: /campaigns
  - :active: false
    :text: Leads
    :url: /leads
  - :active: false
    :text: Contacts
    :url: /contacts

campaign_status:
  :planned:
    :label: Planned
    :color: palegreen
  :started:
    :label: Started
    :color: paleturquoise
  :completed:
    :label: Completed
    :color: bisque
  :on_hold:
    :label: On Hold
    :color: pink
  :called_off:
    :label: Called Off
    :color: thistle

lead_status:
  :new:
    :label: Not contacted
    :color: palegreen
  :contacted:
    :label: Contacted
    :color: paleturquoise
  :converted:
    :label: Converted
    :color: bisque
  :dead:
    :label: Dead
    :color: thistle

lead_source:
  - :campaign: Campaign
  - :cold_call: Cold Call
  - :campaign: Conference
  - :online: Online Marketing
  - :referral: Referral
  - :self: Self Generated
  - :web: Web Site
  - :word_of_mouth: Word of Mouth
  - :other: Other
