# Defaul applications settings to be loaded during installation:
#
#   rake db:settings:load
#
:tabs:
  - :active: true
    :text: Home
    :url: /
  - :active: false
    :text: Accounts
    :url: /accounts
  - :active: false
    :text: Campaigns
    :url: /campaigns
  - :active: false
    :text: Leads
    :url: /leads
  - :active: false
    :text: Contacts
    :url: /contacts

:campaign_types:
  - 
  - Email
  - Webinar
  - Newsletter
  - Conference
  - Trade Show
  - Direct Mail
  - Telemarketing
  - Web Advertisiment
  - Print Advertisiment
  - Radio Advertisiment
  - Other

campaign_stages:
  - 
  - Planned
  - Started
  - Completed
  - On Hold
  - Called Off
